---
title: "Implementing a Megadapt model"
output: html_document
---

# Introduction


## 1. Create component model

  a. Build a constructer.

  c. Define class of the component.

  b. Initialize the states of the class. 

## 1.2. Create functions that consider study data and the states of the class. 

The function take arguments the states of the class, and the study data. THis function will return a data frame with the changes in the columns of a study data specified by the component. These functions will link outcome to changes in the study data. 

The components save all the changes and then a transition function will modify the data frame of the study data. 

## 1.3 Initialization function. 

It create new fields in the data frame if needed, and set initial values for these new variables created. 


# 2. Building a megadapt object

A megadapt object integrates all the sub-components. In essence the megadapt object is a component with its own "megadapt class". As such the megadapt object has its own class and states that are passed to all the functions fromt he same class. The contruct of the megadapt object is a function that takes as arguments all the other components. 
The initialization function of the megadapt component includes the year of the simulation, alll the other components, and a data frame with the study area.


# 3. Simulating a megadapt object

The ```Simulate()``` function take as argument a megadapt object.
Initialize the magedapt object
Extract the study data
Transition the component using transition function.
loop throught the years according to the state simulation_years, which is an state of the megadapt class.

# 4. Building an institutional agent

A main component in building a megadapt model is to build a institutional agent. Institutional agents are decition-makers that impact the state of the landscape acording to the decisions. 

An institutional agent must contains a set of routines and input data to determines the areas where investments are more needed.  These routines include data to define tranformation of attributes to value functions, mental model strategy with criteria and actions, and attributes changed by decisions. A set of parameter values that include budgets, and a set of routines to  create a work plan for investments and for selection of areas for invetments.


