---
title: "A method to change the unweighted supermatrix from the sewer system in the block {risk, environment}"
date: "May 27, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Equations to implement the double coupling using the rate of change in ponding and flooding from historic mean in the city

## To change the values in the column rainfall 
$rf$.

First, we calculate the rate of change from historical values and we multiply it by the initial weights in the column $rf$ of the environment block of the unweighted supermatrix: 
$$\Omega_{p,t}^{rf} =\frac{\sum pond_{j,t}}{\sum \overline{pond_{j}}} w_{initial}^{p,rf}$$


$$\Omega_{f,t}^{rf} =\frac{\sum flood_{j,t}}{\sum \overline{f_{j}}} w_{initial}^{f,rf},$$


$\forall j \in J$ where $J$ is the total number of census block with rainfall. $\Omega_{f,t}^{rf}$ is the unnormalized new weight in the column rainfall ($rf$) and row flooding ($f$) at time $t$. $w_{initial}^{p,rf}$ and $w_{initial}^{f,rf}$ are the initial values in the unweighted matrix for the column rainfall ($rf$) and row ponding ($p$) and flooding ($f$) respectively.
Thus, the new values of the column "precipitation"" in the block {risk, environment} will be:  

$$w_{new,t+1}^{p,rf}=\frac{\Omega_{p,t}^{rf}}{\Omega_{p,t}^{rf} + \Omega_{f,t}^{rf}}$$

$$w_{new,t+1}^{f,rf}=\frac{\Omega_{f,t}^{rf}}{\Omega_{p,t}^{rf} + \Omega_{f,t}^{rf}}$$
where $w_{new,t}^{p,rf}$ and $w_{new,t}^{f,rf}$ are the new values for time $t+1$ in the column rainfall $rf$ and rows ponding $p$ and flooding $f$ respectively.

## To change the values in the column runoff 
To implement a change in the column runoff $r$, the calculation only considers the census blocks that are affected by runoff. (The assumption here is that the runoff from one census block from another is negligible in the areas without runoff).

Let's define $I$ as the set of census block affected by runoff, such that $I \subset J$. The rate of change will be:

$$\Omega_{p,t}^{r} =\frac{\sum pond_{j,t}}{\sum \overline{pond_{i}}} w_{initial}^{p,r}$$


$$\Omega_{f,t}^{r} =\frac{\sum flood_{i,t}}{\sum \overline{flood_{i}}} w_{initial}^{f,r}$$

$\forall i \in I$. 
Thus, the new values of the column "runoff", ($r$), in the block {risk, environment} will be:  

$$w_{new,t+1}^{p,r}=\frac{\Omega_{p,t}^{r}}{\Omega_{p,t}^{r} + \Omega_{f,t}^{r}}$$

$$w_{new,t+1}^{f,r}=\frac{\Omega_{f,t}^{r}}{\Omega_{p,t}^{r} + \Omega_{f,t}^{r}}$$
where $w_{new,t}^{p,r}$ and $w_{new,t}^{f,r}$ are the new values for time $t+1$ in the column runoff $r$ and rows ponding $p$ and flooding $f$ respectively.

