---
title: "PresentationOutline"
author: "Andres Baeza"
date: "May 22, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Model Overview

- show model run
  - maps of different outcomes (vulnerability, investment, risk, social pressure)
  - plots
    - time series of outcomes
    - variability of outcomes
- how is package constructed
- show modularity and R package benefits (documentation, testing, continuous integration)

## Results (Using current implementation)

- show broad trends of impact of budget, initial capacity on outcomes
- sensitivity analysis of budget, initial capacity, infrastructure depreciation

## Ponding and Flooding Functions App

- want to show problems with index functions
- see if delta method implementations work better

## Results (Alternative implementations)

- show model setup (how do you construct different models)
- different model setups
  - double coupling
    - split budget 
    - no budget split
  - single coupling
    - split budget
    - no budget split
  - delta method for ponding and flooding
