---
title: "Site selection and site suitability"
date: "July 3, 2019"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



The decisions of the institutional agent SACMEX is to select a subset of spatial units that maximized the satisfaction of the agent according to the goal of reducing the vulnerability of the city to water-related crisis. The investment decisions by the socio-institutional agents are accomplished in the model by two sub-routines: site suitability and site selection. Site suitability informs the socio-institutional agent as to the best spatial units for investment, based on the criteria and alternatives of the MCDA model. The site selection procedure then evaluates the different alternatives of spatial units in order to identify the set of spatial units that minimized the dissatisfaction after the investment. These investments involve a set of possible actions taken by the socio-institutional agents, $k={k_1,..,k_m}$. Formally, an investment is defined as a Boolean variable, $y_{jt}^k={0,1}$, where the value $y_{jt}^k=1$ represents that an investment associated with action $k$ has been made in the spatial unit $j$ at time $t$. SACMEX decides in which spatial units to allocate investments associated with infrastructure systems to reduce the risk of exposure to hazards at time $t$ in spatial unit $j$.


##Site Suitability

An assessment of the census blocks that are prioritized for actions is obtained through multicriteria evaluation of the distance of each census block from an “ideal point,” or utopian state, defined as a set of decision-making criteria and the relative importance of each criterion for the decision makers (Bojórquez-Tapia et al., 2011). Formally, we calculate a distance d_jvt^k, such that:

$$d_{jt}^{k}={[\alpha^\rho \sum_{i}^{I} w_i^{\rho}  (1-x_{ijt}^{k})^\rho]}^{\frac{1}{\rho}}$$   
where $d_{jt}^{k}$ is the distance to the ideal point of census block $j$ with respect to action $k$; $w_i$ is the criterion weight of criterion $i$, $\alpha$ is the weight of action k; $x_{ijt}$ is the normalized value in a census block $j$ of the attribute corresponding to criterion $i$, with respect to action $k$; $x_{ijt}$ is the departure of an alternative from the ideal point for a criterion. This variable is the standardized score $x_{ijt}$, which represents a judgment about the importance of an observable stimulus (census block attribute value) in the water authority’s decision; $i, j, k, t$, are indices for criteria, census blocks, action, time, respectively. Finally, parameter \rho  is the compensatory parameter that define the metric to compute the distance. With $\rho=2$, the metric is Euclidian. 

## Site selection

Every year site selection is invoked by the manager for choosing investments y_v^k, in action k in system v, in a specific number of census blocks, established by budgetary constraints B_k. Formally, this involves using a 0-1 (or binary) programming model (Dykstra 1984) in which the objective function maximizes d_jvt^k. In this way, the model simulates a preference for investing in the census blocks where investment in infrastructure system v is most needed. Formally:



\begin{equation*}
\begin{aligned}
& \underset{x}{\text{maximize}}
& & F(y_t^k)=\sum_{j}^{J} d_{jt}^{k} y_{jt}^k \\
& \text{subject to}
& & \sum_j^{J} y_{jt}^k <B_k.
\end{aligned}
\end{equation*}



where $B_k$ is the number of census-blocks where investment related to action k can take place; $y_{jt}^k$ is the 0-1 decision variable for action $k$ in census block $j$ at time $t$ ($y_{jt}^k=1$, if census block $j$ is selected for investment, or 0 otherwise). An implementation of other forms of maximization with a more complete set of constrains is underway.
Budget $B$ represents a total capital or resources divided among census blocks. Thus when $B < J$  there is a limited among of resources to be divided in the city. The budget can be aggregated or disaggregated according to institutional rules. For instance, in CDMX the budget for drainage is separated from the budget for potable water system, and within each system, the budget is divided in actions. The optimization of the objective functions were done using a non-dominant sorting assessment (NDSA) that find solutions near the Pareto frontier.

