language: r
r:
  - release
sudo: required
latex: false
pandoc: 1.19.2.1
notifications:
  email: comses-dev@googlegroups.com
apt_packages:
  - zlib1g-dev
  - libpng-dev
  - libgeos-dev
  - libgdal-dev
before_install:
  - cd src/r/megadaptr
script:
  - R CMD build .
  - R CMD check *tar.gz && \
    Rscript -e 'testthat::test_file("../scenarios/test_model_run.R")'
warnings_are_errors: false
