language: r
r:
  - release
sudo: required
latex: false
pandoc: 1.19.2.1
notifications:
  email: comses-dev@googlegroups.com
apt_packages:
  - zlib1g-dev
  - libpng-dev
  - libgeos-dev
  - libgdal-dev
before_install:
  - cd src/r/megadaptr
install:
  - R -e "install.packages(c('devtools', 'roxygen2'))"
  - R -e "devtools::install_deps()"
  - R -e "devtools::document()"
