language: r
r:
  - release
sudo: required
latex: false
pandoc: false
notifications:
  email: comses-dev@googlegroups.com
services:
  - docker
env: 
  - DOCKER_COMPOSE_VERSION=1.23.2
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y docker-ce
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod a+rx docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo sysctl -w vm.max_map_count=262144
script:
  - bash src/netlogo/run.sh
