language: r
r:
  - release
sudo: required
latex: false
pandoc: 1.19.2.1
env:
  R_INTEGRATION_TESTS="yes"
notifications:
  email: comses-dev@googlegroups.com
before_install:
  - cd src/r/megadaptr
install:
  - sudo apt-get install -y zlib1g-dev libpng-dev libgeos-dev libgdal-dev
  - R -e "install.packages(c('devtools', 'roxygen2'))"
  - R -e "devtools::install_deps(dependencies = TRUE)"
  - R -e "devtools::document()"
