version: '3'
services:
  megadapt:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PASSWORD: test
    ports:
      - "127.0.0.1:8787:8787"
    volumes:
      - "./VBSAMatrices:/home/rstudio/code/VBSAMatrices"
      - "./output:/home/rstudio/code/output"
      - "./src/r:/home/rstudio/code/src/r"
