version: "3.6"
services:
  shiny:
    build:
      context: ../../..
      dockerfile: src/r/webapp/Dockerfile
    ports:
      - "127.0.0.1:3000:3838"
    volumes:
      - "../../../data:/srv/data"
      - "./log:/var/log/shiny-server"
